@startuml

state ReduxStore {
  state "todos" as ReduxValue1
  state "viFilter" as ReduxValue2
}
state connect
state Provider

state TodosStore {
  state "todos" as SvelteValue1
}
state ViFilterStore {
  state "viFilter" as SvelteValue2
}
state useStore
useStore: [state, set]
state useReducerStore
useReducerStore: [state, dispatch]

state Component
' Redux path
Component -[#red]-> connect: mapXxxToProps
connect --> Provider
Provider --> ReduxStore: subscribe, dispatch

' Svelte path
Component -[#orange]-> useStore
Component -[#green]-> useReducerStore: useReducerStore
useReducerStore --> useStore: useStore
useStore --> TodosStore: subscribe, set
useStore --> ViFilterStore: subscribe, set
@enduml